# Generated by Django 5.0.1 on 2024-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
