# Generated by Django 5.0.1 on 2024-03-04 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mpr', '0004_delete_login_delete_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30)),
                ('view_password', models.CharField(max_length=50)),
                ('view_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, null=True)),
                ('cemail', models.EmailField(max_length=254, null=True)),
                ('cphone', models.CharField(max_length=30, null=True)),
                ('c_status', models.CharField(default='pending', max_length=30)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.login')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30, null=True)),
                ('semail', models.EmailField(max_length=254, null=True)),
                ('sphone', models.CharField(max_length=30, null=True)),
                ('s_status', models.CharField(default='pending', max_length=30)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.login')),
            ],
        ),
    ]
