# Generated by Django 5.0.1 on 2024-03-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
