# Generated by Django 5.0.1 on 2024-03-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0006_login_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30, null=True)),
                ('pcategory', models.CharField(max_length=30, null=True)),
                ('pdetails', models.CharField(max_length=30, null=True)),
                ('bidDate', models.DateField()),
                ('price', models.CharField(max_length=30)),
                ('productBidstatus', models.CharField(default='pending', max_length=20)),
                ('productSeller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.customer')),
            ],
        ),
    ]
