# Generated by Django 5.0.1 on 2024-03-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0008_products_pemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cemail',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
