# Generated by Django 5.0.1 on 2024-03-06 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0009_alter_customer_cemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidAmount', models.CharField(max_length=30)),
                ('bidstatus', models.CharField(default='pending', max_length=20)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.products')),
            ],
        ),
    ]
