# Generated by Django 5.0.1 on 2024-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0010_bidtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidtable',
            name='seller_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
