# Generated by Django 5.0.1 on 2024-03-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0011_bidtable_seller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=100)),
                ('artistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpr.customer')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpr.seller')),
            ],
        ),
    ]
