# Generated by Django 5.0.1 on 2024-03-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0013_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
