# Generated by Django 5.0.1 on 2024-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0015_onlineauction'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineauction',
            name='ampm',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='onlineauction',
            name='bidTime',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
