# Generated by Django 5.0.1 on 2024-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0016_onlineauction_ampm_onlineauction_bidtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineauction',
            name='bidTime',
            field=models.TimeField(max_length=30, null=True),
        ),
    ]
