# Generated by Django 5.0.1 on 2024-03-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0017_alter_onlineauction_bidtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineauction',
            name='bidTime',
            field=models.TimeField(null=True),
        ),
    ]
