# Generated by Django 5.0.1 on 2024-03-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0021_remove_onlineauctionbidtable_utype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineauctionbidtable',
            old_name='pname',
            new_name='cpname',
        ),
    ]
