# Generated by Django 5.0.1 on 2024-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0022_rename_pname_onlineauctionbidtable_cpname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineauctionbidtable',
            name='artistid',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='onlineauctionbidtable',
            name='uid',
            field=models.CharField(max_length=300),
        ),
    ]
