# Generated by Django 5.0.1 on 2024-03-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0023_alter_onlineauctionbidtable_artistid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineauctionbidtable',
            old_name='cpname',
            new_name='cname',
        ),
    ]
