# Generated by Django 5.0.1 on 2024-03-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0025_onlineauctionbidtable_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineauctionbidtable',
            name='pname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
