# Generated by Django 5.0.1 on 2024-03-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0026_alter_onlineauctionbidtable_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_pimage',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_pimage',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
