# Generated by Django 5.0.1 on 2024-04-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0027_customer_customer_pimage_seller_seller_pimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionroom',
            name='artistid',
        ),
        migrations.RemoveField(
            model_name='auctionroom',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='bidtable',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bidtable',
            name='product',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='artistid',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='onlineauction',
            name='productSeller',
        ),
        migrations.DeleteModel(
            name='onlineAuctionBidTable',
        ),
        migrations.RemoveField(
            model_name='products',
            name='productSeller',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
        migrations.DeleteModel(
            name='auctionroom',
        ),
        migrations.DeleteModel(
            name='BidTable',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='onlineAuction',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
