# Generated by Django 5.0.1 on 2024-04-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0028_remove_auctionroom_artistid_remove_auctionroom_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Phonenumber', models.IntegerField()),
                ('Password', models.CharField(max_length=20)),
                ('Image', models.ImageField(null=True, upload_to='Image')),
                ('Address', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.login')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
