# Generated by Django 5.0.1 on 2024-04-12 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0030_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
                ('Phone', models.IntegerField(max_length=10, null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Time', models.TimeField()),
                ('am_pm', models.CharField(max_length=2, null=True)),
                ('Service', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mpr.user')),
            ],
        ),
    ]
