# Generated by Django 5.0.1 on 2024-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0031_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
