# Generated by Django 5.0.1 on 2024-04-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0034_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
